Resources:
  WelcomeHandlerServiceRoleA03808BE:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: LambdaGatewayStack/WelcomeHandler/ServiceRole/Resource
  WelcomeHandlerBD29C4C1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-101751915105-us-east-1
        S3Key: 9f253141b6a0dc65699add447674a160ba0ed1792ad52078d064393883c55b5a.zip
      Handler: welcome.handler
      Role:
        Fn::GetAtt:
          - WelcomeHandlerServiceRoleA03808BE
          - Arn
      Runtime: python3.10
    DependsOn:
      - WelcomeHandlerServiceRoleA03808BE
    Metadata:
      aws:cdk:path: LambdaGatewayStack/WelcomeHandler/Resource
      aws:asset:path: asset.9f253141b6a0dc65699add447674a160ba0ed1792ad52078d064393883c55b5a
      aws:asset:is-bundled: false
      aws:asset:property: Code
  EndpointEEF1FD8F:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Endpoint
    Metadata:
      aws:cdk:path: LambdaGatewayStack/Endpoint/Resource
  EndpointDeployment318525DA5a27859679c3686c4c85c0f3ad030899:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: EndpointEEF1FD8F
    DependsOn:
      - EndpointproxyANYC09721C5
      - Endpointproxy39E2174E
      - EndpointANY485C938B
    Metadata:
      aws:cdk:path: LambdaGatewayStack/Endpoint/Deployment/Resource
  EndpointDeploymentStageprodB78BEEA0:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: EndpointDeployment318525DA5a27859679c3686c4c85c0f3ad030899
      RestApiId:
        Ref: EndpointEEF1FD8F
      StageName: prod
    Metadata:
      aws:cdk:path: LambdaGatewayStack/Endpoint/DeploymentStage.prod/Resource
  Endpointproxy39E2174E:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: LambdaGatewayStack/Endpoint/Default/{proxy+}/Resource
  EndpointproxyANYApiPermissionLambdaGatewayStackEndpoint5CAA3659ANYproxy8C350A96:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WelcomeHandlerBD29C4C1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:101751915105:"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/*
    Metadata:
      aws:cdk:path: LambdaGatewayStack/Endpoint/Default/{proxy+}/ANY/ApiPermission.LambdaGatewayStackEndpoint5CAA3659.ANY..{proxy+}
  EndpointproxyANYApiPermissionTestLambdaGatewayStackEndpoint5CAA3659ANYproxy0709027B:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WelcomeHandlerBD29C4C1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:101751915105:"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: LambdaGatewayStack/Endpoint/Default/{proxy+}/ANY/ApiPermission.Test.LambdaGatewayStackEndpoint5CAA3659.ANY..{proxy+}
  EndpointproxyANYC09721C5:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - WelcomeHandlerBD29C4C1
                  - Arn
              - /invocations
      ResourceId:
        Ref: Endpointproxy39E2174E
      RestApiId:
        Ref: EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: LambdaGatewayStack/Endpoint/Default/{proxy+}/ANY/Resource
  EndpointANYApiPermissionLambdaGatewayStackEndpoint5CAA3659ANYFC850675:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WelcomeHandlerBD29C4C1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:101751915105:"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/
    Metadata:
      aws:cdk:path: LambdaGatewayStack/Endpoint/Default/ANY/ApiPermission.LambdaGatewayStackEndpoint5CAA3659.ANY..
  EndpointANYApiPermissionTestLambdaGatewayStackEndpoint5CAA3659ANY439C72A1:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - WelcomeHandlerBD29C4C1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:101751915105:"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: LambdaGatewayStack/Endpoint/Default/ANY/ApiPermission.Test.LambdaGatewayStackEndpoint5CAA3659.ANY..
  EndpointANY485C938B:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - WelcomeHandlerBD29C4C1
                  - Arn
              - /invocations
      ResourceId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      RestApiId:
        Ref: EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: LambdaGatewayStack/Endpoint/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/01O207DMAz9lr2nZmxCgscNxNMQVfmAKUtNCW2SqnY0qij/TpIO1Kdzsc+xd/D4BNuNvFKl2r4a9AXCB0vVi2SdwyDNpZUQXr1VrJ0Vz592zWucjCZKKgotDYTGDZgHGaOg/VkSIRMcMiQNR6965KMkFHLUnWS8yhnCqRxqkPgw6lJwoy84Dm42aDm7K5W+7MqphaR95yeFpbme3M/859zaFv6G/OXabC0sxv+kKD/mNm27vPHuefS8jkdRzyll7/Zwv4WHzTdpXU3esjYIzYK/SScv8FIBAAA=
    Metadata:
      aws:cdk:path: LambdaGatewayStack/CDKMetadata/Default
Outputs:
  Endpoint8024A810:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: EndpointEEF1FD8F
          - .execute-api.us-east-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: EndpointDeploymentStageprodB78BEEA0
          - /
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

